version: 5.4.{build}
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: +TzX/BKrTfQGbBDkoq8kAlwcyMX3kHkwad40Dl5svZRVUIzVQ0fKrY1+7Go4i9un
  on:
    branch: master